In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("fdt_dataset_100_rows.xlsx")
df.head()

,Formulation,Superdisintegrant,Concentration (%),Binder (%),Compression (kN),Disintegration Time (sec)
0,F1,CP,5,2,6,25.0
1,F2,CCS,2,4,5,45.0
2,F3,CP,4,4,7,33.0
3,F4,CP,3,2,5,38.0
4,F5,SSG,3,3,7,35.5

In [8]:
df.shape

(100, 6)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Formulation                100 non-null    object
 1   Superdisintegrant          100 non-null    object
 2   Concentration (%)          100 non-null    int64
 3   Binder (%)                 100 non-null    int64
 4   Compression (kN)           100 non-null    int64
 5   Disintegration Time (sec)  100 non-null    float64
dtypes: float64(1), int64(3), object(2)
memory usage: 4.8+ KB

In [10]:
df.describe()

,Concentration (%),Binder (%),Compression (kN),Disintegration Time (sec)
count,100.000000,100.000000,100.000000,100.000000
mean,3.630000,3.480000,5.670000,35.150000
std,1.116045,1.123487,1.163893,7.397618
min,2.000000,2.000000,4.000000,21.000000
25%,3.000000,2.000000,5.000000,29.500000
50%,4.000000,3.500000,6.000000,34.500000
75%,5.000000,4.000000,7.000000,40.500000
max,5.000000,5.000000,7.000000,49.500000

In [11]:
df.isnull().sum()

Formulation                  0
Superdisintegrant            0
Concentration (%)            0
Binder (%)                   0
Compression (kN)             0
Disintegration Time (sec)    0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Define input and output
X = df.drop(columns=["Formulation", "Disintegration Time (sec)"])
y = df["Disintegration Time (sec)"]

# Identify categorical column
categorical_cols = ["Superdisintegrant"]
numeric_cols = ["Concentration (%)", "Binder (%)", "Compression (kN)"]

# Encoding categorical data
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(drop="first"), categorical_cols),
        ("num", "passthrough", numeric_cols)
    ]
)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [25]:
from sklearn.ensemble import RandomForestRegressor

# Create pipeline (preprocessing + model)
model = Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("regressor", RandomForestRegressor(n_estimators=100, random_state=42))
])

# Train model
model.fit(X_train, y_train)

print("Model Training Completed")

Model Training Completed

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Predictions
y_pred = model.predict(X_test)

# Metrics
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", round(mae,2))
print("RMSE:", round(rmse,2))
print("R2 Score:", round(r2,2))

MAE: 1.84
RMSE: 2.35
R2 Score: 0.88

In [30]:
import joblib

In [31]:
joblib.dump(model,"fdt_rf_model.pkl")
print("model save successdully ")

model save successdully